### ISSUE TITLE
Password Field

### ISSUE THREAD

**Issue by ForgivenNin** [cyruscook/emailer#1]
Why is the password field required for the php script to work?
It doesn't seem like the password would ever be used again once the email is sent.

**Comment by cyruscook** [comment]
check https://github.com/cyruscook/emailer/blob/master/index.php#L3 , I wrote a comment detailing the purpose of the password

**Comment by cyruscook** [comment]
Also to add to that comment, always make sure that any time a user can trigger code on the server there is some form of protection, be it captcha, DDOS mitigation or password protection.

**Comment by ForgivenNin** [comment]
Oh okay, I see. My vision of it was that this application could be used in a client-sided manner.

_(However, it seems like the password variable is implemented throughout the script. So I'm not sure how I'll work around that, but I'm gonna go ahead and try anyways. Please let me know if you have any suggestions.)_

**Comment by cyruscook** [comment]
The web browser cannot send emails, you need a server to do that
